server:
  port: 8100
  
  
#  cloud:
#    gateway:
      
  
spring:
  config.import: configserver:http://localhost:8888/
  application.name: APIGateway
  main.web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
         - id: order-service
           uri: lb://ORDER-SERVICE
           predicates:
           - Path=/orders/**
         - id: user-service
           uri: lb://USER-SERVICE
           predicates:
           - Path=/users/**
         - id: admin-service
           uri: lb://ADMIN-SERVICE
           predicates:
           - Path=/report/**
#        - id: movieinfo
#          uri: lb://movie-info-service
#          predicates:
#          - Path=/movies/**
#        - id: ratingsservice1
#          uri: lb://ratings-data-service
#          predicates:
#          - Path=/ratingsdata/movies/**
#        - id: ratingsservice2
#          uri: lb://ratings-data-service
#          predicates:
#          - Path=/ratingsdata/user/**
         - id: washer-service
           uri: lb://WASH-PACK-SERVICE
           predicates:
           - Path=/washers/**
          
         - id: dicovery-server
           uri: http://localhost:${eureka.port:8761}
           predicates:
           - Path=/
 #config.import: configserver:http://localhost:8888
  
management:
  endpoints:
    web.exposure.include: health,info,refresh
    
eureka:
  port: 8761

  