server.port: 8083

spring:
 application:
  name: USER-SERVICE
 config.import: configserver:http://localhost:8888/
 data.mongodb:
  uri: mongodb+srv://Dipanwita:newpassword@clusterdipanwita.w8vrb7e.mongodb.net/?
  database: UserDatabase
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
   
   
   


springdoc:
  swagger-ui:
    path: /users/swagger
