server.port: 8084

spring:
 application:
  name: ADMIN-SERVICE
 config.import: configserver:http://localhost:8888/
 data.mongodb:
  uri: mongodb+srv://Dipanwita:newpassword@clusterdipanwita.w8vrb7e.mongodb.net/?
  database: AdminDatabase
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER
   
   
   
   
springdoc:
  swagger-ui:
    path: /admins/swagger
